version: '3'

services:

  annotator_api:
    container_name: annotator-api
    restart: always
    build: ./annotator
    ports:
      - "5555:5000"
    command: gunicorn -w 1 -b :5000 server:app

  # annotator_ui:
  #   container_name: annotator-ui
  #   restart: always
  #   build: ./ui
  #   ports:
  #     - "6776:8080"
  #   # command: yarn serve
  #   depends_on:
  #     - annotator_api
  
  
  